lab_name: NSFW_PurpleLab
description: "Purple team VM lab to test Azure/OpenAI-powered polymorphic fileless DLL malware with telemetry and threat detection."
infrastructure:
  platform: Hyper-V
  base_image: "Windows 11 Pro Eval"
  snapshot_enabled: true
  network:
    - name: NSFW-LAN
      type: internal
      ip_range: "192.168.66.0/24"
      allow_internet: true

vms:
  - name: Target-Win11
    role: victim
    image: windows-11-pro
    memory: 8GB
    cpus: 4
    ip: 192.168.66.10
    users:
      - username: attacker
        password: "P@ssw0rd123!"
    tools:
      preinstalled:
        - SysinternalsSuite
        - PowerShell v7
        - Visual C++ Redistributables
        - Donut (CLI)
        - Git
      scripts:
        - name: Install-Sysmon
          run_as_admin: true
          script: |
            iwr -Uri https://download.sysinternals.com/files/Sysmon.zip -OutFile sysmon.zip
            Expand-Archive sysmon.zip -DestinationPath C:\Tools\Sysmon
            .\C:\Tools\Sysmon\Sysmon.exe -accepteula -i C:\Tools\Sysmon\sysmonconfig-export.xml
        - name: Enable-SecLogging
          run_as_admin: true
          script: |
            auditpol /set /category:* /success:enable /failure:enable
            Set-ItemProperty -Path "HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application" -Name MaxSize -Value 32768
    defenders:
      microsoft_defender:
        real_time_protection: true
        sample_submission: false
        exclusions:
          - "C:\\payloads"
          - "C:\\Tools"

  - name: Logger-ELK
    role: siem
    image: ubuntu-22.04
    memory: 6GB
    cpus: 2
    ip: 192.168.66.20
    tools:
      install:
        - logstash
        - kibana
        - elasticsearch
        - filebeat
        - suricata
    config_scripts:
      - name: Configure-ELK
        script: |
          sudo systemctl enable elasticsearch
          sudo systemctl enable kibana
          sudo systemctl enable logstash
          # Preload Sigma rules
          git clone https://github.com/SigmaHQ/sigma.git /opt/sigma

  - name: AzureBridge
    role: cloud_bridge
    image: ubuntu-20.04
    memory: 4GB
    cpus: 2
    ip: 192.168.66.30
    tools:
      install:
        - azure-cli
        - python3
        - pip
    scripts:
      - name: Deploy-BlobMonitor
        script: |
          az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_SECRET --tenant $AZURE_TENANT_ID
          az functionapp deployment source config-zip -g NSFW-RG -n NSFWFunctionApp --src ./azure/polymorph_dispatch.zip

shared_folders:
  - name: NSFW-Payloads
    path_host: ./payload/
    path_guest: C:\payloads
    mount_to:
      - Target-Win11

monitoring:
  - type: Sysmon
    enabled: true
    target: Target-Win11
  - type: Sigma
    enabled: true
    location: /opt/sigma
    siem_target: Logger-ELK
  - type: LOLBinsDetection
    enabled: true
    custom:
      include_bins:
        - rundll32.exe
        - regsvr32.exe
        - mshta.exe

tags:
  - "purple"
  - "fileless"
  - "dll-injection"
  - "polymorphic"
  - "Azure"
