lab_name: NSFW_PurpleLab_Extended

description: >
  Extended purple team simulation lab for NSFW (Net Sharing Fileless Wiperware)
  that includes:
    - Fileless reflective DLL injection
    - LOLBins delivery (rundll32, regsvr32, mshta)
    - AES-XTS DiskCryptor-based encryption wiper
    - Polymorphic mutation via Azure OpenAI Agent (CV032 / GUMI)
    - Deepfake TTS + Voice Cloning using Azure AI
    - AI-powered shapeshifting payloads using image/audio synthesis
    - ELK + Sigma + Sysmon telemetry
    - Azure DevOps pipeline + Function deployment

infrastructure:
  platform: Hyper-V
  base_image: "Windows 11 Pro Eval"
  network:
    - name: NSFW-LAN
      type: internal
      ip_range: "192.168.66.0/24"

vms:
  - name: Target-Win11
    role: victim
    image: windows-11-pro
    memory: 8GB
    cpus: 4
    ip: 192.168.66.10
    users:
      - username: attacker
        password: "P@ssw0rd123!"
    tools:
      preinstalled:
        - PowerShell v7
        - Git
        - SysinternalsSuite
        - Visual C++ Redistributables
        - Azure Cognitive Services Voice SDK
      scripts:
        - name: Enable-SecurityLogs
          script: |
            auditpol /set /category:* /success:enable /failure:enable
        - name: Install-Sysmon
          script: |
            iwr -Uri https://download.sysinternals.com/files/Sysmon.zip -OutFile sysmon.zip
            Expand-Archive sysmon.zip -DestinationPath C:\Tools\Sysmon
            .\C:\Tools\Sysmon\Sysmon.exe -accepteula -i C:\Tools\Sysmon\sysmonconfig.xml

  - name: Logger-ELK
    role: siem
    image: ubuntu-22.04
    memory: 6GB
    cpus: 2
    ip: 192.168.66.20
    tools:
      install:
        - elasticsearch
        - kibana
        - logstash
        - filebeat
        - suricata

  - name: AzureAI-CV032
    role: ai_dev_agent
    image: ubuntu-22.04
    memory: 4GB
    cpus: 2
    ip: 192.168.66.30
    tools:
      install:
        - azure-cli
        - python3
        - pip
        - git
        - ffmpeg
      scripts:
        - name: Setup-AI-Suite
          script: |
            pip install openai azure-identity azure-cognitiveservices-speech
            git clone https://github.com/YourRepo/NSFW /opt/NSFW
            echo "from openai import AzureOpenAI\n# Deepfake voice, image morphing, and DLL generation logic here" > /opt/NSFW/ai/cv032_agent.py

shared_folders:
  - name: NSFW-Source
    path_host: ./NSFW/
    path_guest: C:\payloads
    mount_to:
      - Target-Win11

monitoring:
  - type: Sysmon
    enabled: true
    target: Target-Win11
  - type: Sigma
    enabled: true
    location: /opt/sigma
    siem_target: Logger-ELK

automation:
  pipeline:
    tool: Azure DevOps
    trigger: "push"
    stages:
      - name: Build_Mutate_AudioDeepfake_DLL
        agent: AzureAI-CV032
        script: |
          python3 /opt/NSFW/ai/cv032_agent.py --deepfake --dll --voiceclone
      - name: Deploy_to_VM
        target: Target-Win11
        script: |
          rundll32.exe C:\payloads\encryptor.dll,EntryPoint
      - name: AzureFunction_Push
        target: AzureAI-CV032
        script: |
          az functionapp deployment source config-zip -g NSFW-RG -n NSFWFunctionApp --src /opt/NSFW/build/deepfake_payload.zip

tags:
  - fileless
  - polymorphic
  - shapeshifting
  - diskcryptor
  - reflective-dll
  - ai-agent
  - deepfake
  - tts
  - mitre-attack
